# Generated by Django 6.0.3 on 2026-04-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dailysteps'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='water_glasses',
            field=models.IntegerField(default=0),
        ),
    ]
