# Generated by Django 6.0.3 on 2026-04-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_sleep_hours_userprofile_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_tracker_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
