# Generated by Django 6.0.3 on 2026-04-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0002_meal_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.AddField(
            model_name='food',
            name='calories_per_100g',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], default='breakfast', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.FloatField(default=100),
        ),
    ]
