# Generated by Django 6.0.4 on 2026-05-06 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_remove_food_calories_food_calories_per_100g_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
